# .pre-commit-config.yaml
# Pre-commit hooks for Tengingarstjóri SSH Connection Manager
# Install with: pre-commit install

repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        description: Trim trailing whitespace
      - id: end-of-file-fixer
        description: Ensure files end with newline
      - id: check-yaml
        description: Validate YAML files
      - id: check-toml
        description: Validate TOML files
      - id: check-json
        description: Validate JSON files
      - id: check-merge-conflict
        description: Check for merge conflict markers
      - id: check-case-conflict
        description: Check for case conflicts
      - id: check-executables-have-shebangs
        description: Ensure executables have shebangs
      - id: mixed-line-ending
        description: Check for mixed line endings

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        description: Format Python code with Black
        args: [--line-length=88, --target-version=py39]

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        description: Sort Python imports
        args: [--profile=black, --line-length=88]

  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        description: Lint Python code with flake8
        args:
          - --max-line-length=88
          - --ignore=E203,W503,E501
          - --max-complexity=10
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
